const SHEET_ID='1vlJodWTnj5TvaO7fkVbteeJ0Hb5WP2Ta-MINeFA3Wks';
const VERSION='13';
const DEFAULT_ADMIN_PASSWORD='BNAADMIN2026';
const SHEETS={Students:['Timestamp','Student ID','Name','Email','Phone','DOB','Address','Status'],Enrollments:['Timestamp','Student ID','Course ID','Course','Subjects','Enrollment Status','Payment Status'],Payments:['Timestamp','Student ID','Course ID','Course','Amount','Payment ID','Order ID','Payment Status'],Results:['Timestamp','Student ID','Name','Course ID','Course','Subject','Score','Total','Percentage','Result','Exam ID'],Certificates:['Timestamp','Student ID','Name','Course ID','Course','Certificate No','Grade','Issued At','Verification URL']};
const COURSES=[[1,'Computer Fundamentals',999],[2,'Basic Computer & Internet',999],[3,'MS Office',1499],[4,'MS Word',999],[5,'MS Excel',1299],[6,'MS PowerPoint',999],[7,'Internet & Email',799],[8,'Typing — English',799],[9,'Typing — Punjabi',799],[10,'Digital Literacy',799],[11,'Advanced Excel',1499],[12,'Tally Prime',1999],[13,'Tally + GST',2499],[14,'Computerized Accounting',2499],[15,'Data Entry Operator',1499],[16,'Office Assistant',1499],[17,'Computer Operator',1499],[18,'DTP — Desktop Publishing',1499],[19,'Photoshop',1499],[20,'CorelDRAW',1499],[21,'Canva & Graphic Designing',1499],[22,'Web Designing',1999],[23,'HTML & CSS',1499],[24,'JavaScript',1999],[25,'WordPress',1499],[26,'Full Stack Web Development',3999],[27,'Python Programming',2499],[28,'C Programming',1499],[29,'C++ Programming',1499],[30,'Java Programming',2499],[31,'Database / MySQL',1499],[32,'Graphic Designing',1999],[33,'Video Editing',1999],[34,'Digital Marketing',1999],[35,'Social Media Marketing',1999],[36,'UI/UX Designing',2499],[37,'Animation Basics',1999],[38,'Cyber Security Basics',2499],[39,'Networking Basics',1999],[40,'Computer Hardware & Networking',2499],[41,'Cloud Computing Basics',2499],[42,'AI Tools & Generative AI',1999],[43,'AI for Office Work',1499],[44,'Data Analytics Basics',2499],[45,'Computer Operator',1499],[46,'Data Entry',1499],[47,'Office Management',1499],[48,'MIS Executive',1999],[49,'Back Office Executive',1499],[50,'Computerized Accounting',2499],[51,'Digital Marketing Executive',1999],[52,'Web Developer',2499],[53,'Graphic Designer',1999]];
function s(v){return v==null?'':String(v).trim();}
function out(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
function setupSheets(){const ss=SpreadsheetApp.openById(SHEET_ID);Object.keys(SHEETS).forEach(n=>{let sh=ss.getSheetByName(n)||ss.insertSheet(n);if(sh.getLastRow()===0)sh.getRange(1,1,1,SHEETS[n].length).setValues([SHEETS[n]]);sh.setFrozenRows(1);});return out({ok:true,version:VERSION});}
function doGet(){return out({ok:true,service:'Baba Nanak Academy API',status:'online',version:VERSION});}
function doPost(e){try{if(!e||!e.postData||!e.postData.contents)return out({ok:false,message:'No request data received.'});const b=JSON.parse(e.postData.contents||'{}'),a=s(b.action||b.event),d=b.data||{},ss=SpreadsheetApp.openById(SHEET_ID);if(a==='courses')return out({ok:true,courses:COURSES.map(c=>({id:c[0],name:c[1],fee:c[2]}))});if(a==='register')return out(register(ss,d));if(a==='verifyStudent')return out(verifyStudent(ss,d));if(a==='createRazorpayOrder')return out(createRazorpayOrder(d));if(a==='verifyRazorpayPayment')return out(verifyRazorpayPayment(ss,d));if(a==='studentDashboard')return out(studentDashboard(ss,d));if(a==='adminLogin')return out(adminLogin(d));if(a==='adminData'){requireAdmin(d);return out(adminData(ss));}if(a==='adminResult'){requireAdmin(d);saveResult(ss,d);return out({ok:true,message:'Result saved.'});}if(a==='adminCertificate'){requireAdmin(d);return out({ok:true,certificateNo:saveCertificate(ss,d)});}return out({ok:false,message:'Unknown action: '+a});}catch(err){return out({ok:false,message:s(err&&err.message?err.message:err)});}}
function prop(n,f){return s(PropertiesService.getScriptProperties().getProperty(n))||f;}
function register(ss,d){const name=s(d.name),email=s(d.email).toLowerCase(),phone=s(d.phone).replace(/\D/g,''),dob=s(d.dob),address=s(d.address);if(!name)throw Error('Full Name is required.');if(!/^[6-9][0-9]{9}$/.test(phone))throw Error('Enter a valid 10-digit mobile number.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Enter a valid email address.');const sh=sheet(ss,'Students'),rows=sh.getDataRange().getValues();for(let i=1;i<rows.length;i++){if(s(rows[i][3]).toLowerCase()===email)throw Error('This email is already registered.');if(s(rows[i][4]).replace(/\D/g,'')===phone)throw Error('This mobile number is already registered.');}const id=nextId(sh);sh.appendRow([new Date(),id,name,email,phone,dob,address,'Registered']);return{ok:true,studentId:id,name,email,message:'Registration successful.'};}
function nextId(sh){const p='BNA'+new Date().getFullYear();let m=0;if(sh.getLastRow()>1)sh.getRange(2,2,sh.getLastRow()-1,1).getValues().flat().forEach(v=>{const x=s(v).match(new RegExp('^'+p+'(\\d{5})$'));if(x)m=Math.max(m,+x[1]);});return p+String(m+1).padStart(5,'0');}
function verifyStudent(ss,d){const id=s(d.studentId).toUpperCase(),email=s(d.email).toLowerCase();if(!id||!email)throw Error('Student ID and registered email are required.');const r=sheet(ss,'Students').getDataRange().getValues();for(let i=1;i<r.length;i++)if(s(r[i][1]).toUpperCase()===id&&s(r[i][3]).toLowerCase()===email)return{ok:true,message:'Student verified.',student:{studentId:id,name:s(r[i][2]),email:s(r[i][3]),phone:s(r[i][4]),status:s(r[i][7])}};return{ok:false,message:'Student ID and email do not match.'};}
function course(id){id=+id;return COURSES.find(c=>c[0]===id)||null;}
function createRazorpayOrder(d){const id=s(d.studentId).toUpperCase(),c=course(d.courseId),kid=prop('RAZORPAY_KEY_ID'),sec=prop('RAZORPAY_KEY_SECRET');if(!id||!c)throw Error('Valid student and course are required.');if(!kid||!sec)throw Error('Razorpay keys are not configured in Script Properties.');const payload={amount:c[2]*100,currency:'INR',receipt:('BNA_'+id+'_'+Date.now()).substring(0,40),notes:{student_id:id,course_id:String(c[0])}},auth=Utilities.base64Encode(kid+':'+sec),r=UrlFetchApp.fetch('https://api.razorpay.com/v1/orders',{method:'post',contentType:'application/json',headers:{Authorization:'Basic '+auth},payload:JSON.stringify(payload),muteHttpExceptions:true}),o=JSON.parse(r.getContentText()||'{}');if(r.getResponseCode()<200||r.getResponseCode()>=300)throw Error(o.error&&o.error.description?o.error.description:'Razorpay order failed.');return{ok:true,keyId:kid,orderId:o.id,amount:payload.amount,currency:'INR',course:{id:c[0],name:c[1],fee:c[2]}};}
function verifyRazorpayPayment(ss,d){const id=s(d.studentId).toUpperCase(),c=course(d.courseId),pid=s(d.razorpay_payment_id),oid=s(d.razorpay_order_id),sig=s(d.razorpay_signature),sec=prop('RAZORPAY_KEY_SECRET');if(!id||!c||!pid||!oid||!sig)throw Error('Payment verification data is incomplete.');if(!sec)throw Error('Razorpay secret is not configured.');if(hex(Utilities.computeHmacSha256Signature(oid+'|'+pid,sec))!==sig)throw Error('Payment verification failed.');sheet(ss,'Payments').appendRow([new Date(),id,c[0],c[1],c[2],pid,oid,'Paid']);sheet(ss,'Enrollments').appendRow([new Date(),id,c[0],c[1],'','Enrolled','Paid']);return{ok:true,verified:true,message:'Payment verified and course enrolled.'};}
function studentDashboard(ss,d){const v=verifyStudent(ss,d);if(!v.ok)return v;const id=v.student.studentId,rows=n=>sheet(ss,n).getDataRange().getValues().slice(1).filter(r=>s(r[1]).toUpperCase()===id);return{ok:true,student:v.student,enrollments:rows('Enrollments'),payments:rows('Payments'),results:rows('Results'),certificates:rows('Certificates')};}
function adminLogin(d){return s(d.password)===prop('ADMIN_PASSWORD',DEFAULT_ADMIN_PASSWORD)?{ok:true,message:'Admin login successful.'}:{ok:false,message:'Invalid admin password.'};}
function requireAdmin(d){if(s(d.password)!==prop('ADMIN_PASSWORD',DEFAULT_ADMIN_PASSWORD))throw Error('Admin authorization failed.');}
function adminData(ss){return{ok:true,students:sheet(ss,'Students').getDataRange().getValues(),enrollments:sheet(ss,'Enrollments').getDataRange().getValues(),payments:sheet(ss,'Payments').getDataRange().getValues(),results:sheet(ss,'Results').getDataRange().getValues(),certificates:sheet(ss,'Certificates').getDataRange().getValues()};}
function saveResult(ss,d){const score=+d.score||0,total=+d.total||0,p=total?Math.round(score/total*10000)/100:0;sheet(ss,'Results').appendRow([new Date(),s(d.studentId),s(d.name),s(d.courseId),s(d.course),s(d.subject)||'Final Exam',score,total,p,p>=40?'PASS':'FAIL',s(d.examId)]);}
function saveCertificate(ss,d){const sh=sheet(ss,'Certificates'),no=s(d.certificateNo)||('BNA-CERT-'+new Date().getFullYear()+'-'+String(sh.getLastRow()).padStart(5,'0'));sh.appendRow([new Date(),s(d.studentId),s(d.name),s(d.courseId),s(d.course),no,s(d.grade),new Date(),s(d.verificationUrl)]);return no;}
function sheet(ss,n){let sh=ss.getSheetByName(n);if(!sh){sh=ss.insertSheet(n);sh.getRange(1,1,1,SHEETS[n].length).setValues([SHEETS[n]]);sh.setFrozenRows(1);}return sh;}
function hex(a){return a.map(b=>(b<0?b+256:b).toString(16).padStart(2,'0')).join('');}
