const SHEET_ID = '1vlJodWTnj5TvaO7fkVbteeJ0Hb5WP2Ta-MINeFA3Wks';
const VERSION = '18';
const DEFAULT_ADMIN_PASSWORD = '';
const SHEETS = {Students:['Timestamp','Student ID','Name','Email','Phone','DOB','Address','Status'],Courses:['Course ID','Course','Fee','Subjects','Status'],Enrollments:['Timestamp','Student ID','Course ID','Course','Subjects','Enrollment Status','Payment Status'],Payments:['Timestamp','Student ID','Course ID','Course','Amount','Payment ID','Order ID','Payment Status'],Results:['Timestamp','Student ID','Name','Course ID','Course','Subject ID','Subject','Score','Total','Percentage','Result'],Certificates:['Timestamp','Student ID','Name','Course ID','Course','Certificate No','Grade','Issued At','Verification URL']};
const DEFAULT_COURSES=[[1,'Computer Fundamentals'],[2,'Basic Computer & Internet'],[3,'MS Office'],[4,'MS Word'],[5,'MS Excel'],[6,'MS PowerPoint'],[7,'Internet & Email'],[8,'Typing — English'],[9,'Typing — Punjabi'],[10,'Digital Literacy'],[11,'Advanced Excel'],[12,'Tally Prime'],[13,'Tally + GST'],[14,'Computerized Accounting'],[15,'Office Assistant'],[16,'Computer Operator'],[17,'DTP — Desktop Publishing'],[18,'Photoshop'],[19,'CorelDRAW'],[20,'Canva & Graphic Designing'],[21,'Web Designing'],[22,'HTML & CSS'],[23,'JavaScript'],[24,'WordPress'],[25,'Full Stack Web Development'],[26,'Python Programming'],[27,'C Programming'],[28,'C++ Programming'],[29,'Java Programming'],[30,'Database / MySQL'],[31,'Graphic Designing'],[32,'Video Editing'],[33,'Digital Marketing'],[34,'Social Media Marketing'],[35,'UI/UX Designing'],[36,'Animation Basics'],[37,'Cyber Security Basics'],[38,'Networking Basics'],[39,'Computer Hardware & Networking'],[40,'Cloud Computing Basics'],[41,'AI Tools & Generative AI'],[42,'AI for Office Work'],[43,'Data Analytics Basics'],[44,'Data Entry'],[45,'Office Management'],[46,'MIS Executive'],[47,'Back Office Executive'],[48,'Computerized Accounting'],[49,'Digital Marketing Executive'],[50,'Web Developer'],[51,'Graphic Designer'],[52,'Data Entry Operator'],[53,'Computerized Accounting Professional'],[1111,'ADCA']];
const ADCA_SUBJECTS=[['1111-01','Computer Fundamental',100,40],['1111-02','Desktop Publishing',100,40],['1111-03','HTML, C++',100,40],['1111-04','Tally ERP 9.0',100,40],['1111-05','Typing English/Punjabi',100,40],['1111-06','Installation Windows, Windows Ghost, Hardware',100,40],['1111-07','Practical Lab Assignment & Viva-Voce',400,160]];
function s(v){return v==null?'':String(v).trim()}
function out(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function doGet(e){try{const p=e&&e.parameter?e.parameter:{},a=s(p.action||'health'),ss=SpreadsheetApp.openById(SHEET_ID);let r;if(a==='courses')r={ok:true,courses:getCourses(ss),version:VERSION};else if(a==='subjects')r={ok:true,subjects:getSubjects(ss,p.courseId),version:VERSION};else r={ok:true,service:'Baba Nanak Academy API',status:'online',version:VERSION,message:'API is working.'};if(p.callback&&/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(p.callback))return ContentService.createTextOutput(p.callback+'('+JSON.stringify(r)+');').setMimeType(ContentService.MimeType.JAVASCRIPT);return out(r)}catch(err){return out({ok:false,message:s(err&&err.message?err.message:err),version:VERSION})}}
function doPost(e){try{if(!e||!e.postData||!e.postData.contents)return out({ok:false,message:'No request data received.'});const b=JSON.parse(e.postData.contents||'{}'),a=s(b.action||b.event),d=b.data||{},ss=SpreadsheetApp.openById(SHEET_ID);if(a==='setup')return setupSheets();if(a==='courses')return out({ok:true,courses:getCourses(ss)});if(a==='subjects')return out({ok:true,subjects:getSubjects(ss,d.courseId)});if(a==='register'||a==='registration')return out(register(ss,d));if(a==='verifyStudent')return out(verifyStudent(ss,d));if(a==='studentDashboard')return out(studentDashboard(ss,d));if(a==='enrollment')return out(enrollDirect(ss,d));if(a==='adminLogin')return out(adminLogin(d));requireAdmin(d);if(a==='adminData')return out(adminData(ss));if(a==='adminCourseAdd')return out(adminCourseAdd(ss,d));if(a==='adminStudentAdd')return out(adminStudentAdd(ss,d));if(a==='adminPaymentVerify')return out(adminPaymentVerify(ss,d));if(a==='adminResultBulk')return out(adminResultBulk(ss,d));if(a==='adminResult')return out(adminResult(ss,d));if(a==='adminCertificate')return out({ok:true,certificateNo:saveCertificate(ss,d)});return out({ok:false,message:'Unknown action: '+a})}catch(err){return out({ok:false,message:s(err&&err.message?err.message:err)})}}
function prop(n,f){return s(PropertiesService.getScriptProperties().getProperty(n))||f}
function sheet(ss,n){let sh=ss.getSheetByName(n);if(!sh)sh=ss.insertSheet(n);const h=SHEETS[n];if(!h)throw Error('Unknown sheet: '+n);if(sh.getMaxColumns()<h.length)sh.insertColumnsAfter(sh.getMaxColumns(),h.length-sh.getMaxColumns());sh.getRange(1,1,1,h.length).setValues([h]);sh.setFrozenRows(1);return sh}
function setupSheets(){const ss=SpreadsheetApp.openById(SHEET_ID);Object.keys(SHEETS).forEach(n=>sheet(ss,n));seedCourses(ss);ensureADCA(ss);return out({ok:true,version:VERSION,message:'Setup complete. Existing records preserved.'})}
function seedCourses(ss){const sh=sheet(ss,'Courses');if(sh.getLastRow()>1){ensureADCA(ss);return}sh.getRange(2,1,DEFAULT_COURSES.length,5).setValues(DEFAULT_COURSES.map(c=>[c[0],c[1],0,c[0]===1111?'7':'','Active']))}
function ensureADCA(ss){const sh=sheet(ss,'Courses'),rows=sh.getDataRange().getValues();for(let i=1;i<rows.length;i++){if(String(rows[i][0])==='1111'){if(s(rows[i][1])!=='ADCA')sh.getRange(i+1,2).setValue('ADCA');sh.getRange(i+1,3).setValue(0);sh.getRange(i+1,4).setValue('7');sh.getRange(i+1,5).setValue('Active');return}}sh.appendRow([1111,'ADCA',0,'7','Active'])}
function getCourses(ss){seedCourses(ss);ensureADCA(ss);return sheet(ss,'Courses').getDataRange().getValues().slice(1).filter(r=>s(r[4])!=='Inactive').map(r=>({id:r[0],name:s(r[1]),fee:0,subjects:s(r[3]),status:s(r[4])||'Active'}))}
function getSubjects(ss,id){id=s(id);if(id==='1111')return ADCA_SUBJECTS.map(x=>({subjectId:x[0],subject:x[1],maxMarks:Number(x[2]),minPassMarks:Number(x[3])}));const c=course(ss,id);if(c&&c.subjects){try{const p=JSON.parse(c.subjects);if(Array.isArray(p))return p}catch(ignore){}return String(c.subjects).split(',').map((x,i)=>({subjectId:id+'-'+String(i+1).padStart(2,'0'),subject:s(x),maxMarks:100,minPassMarks:40})).filter(x=>x.subject)}return[]}
function register(ss,d){const name=s(d.name),email=s(d.email).toLowerCase(),phone=s(d.phone).replace(/\D/g,''),dob=s(d.dob),address=s(d.address);if(!name)throw Error('Full Name is required.');if(!/^[6-9][0-9]{9}$/.test(phone))throw Error('Enter a valid 10-digit mobile number.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Enter a valid email address.');const sh=sheet(ss,'Students'),rows=sh.getDataRange().getValues();for(let i=1;i<rows.length;i++){if(s(rows[i][3]).toLowerCase()===email)throw Error('This email is already registered.');if(s(rows[i][4]).replace(/\D/g,'')===phone)throw Error('This mobile number is already registered.')}const id=nextId(sh);sh.appendRow([new Date(),id,name,email,phone,dob,address,'Registered']);return{ok:true,studentId:id,name,email,message:'Registration successful.'}}
function adminStudentAdd(ss,d){return register(ss,d)}
function nextId(sh){const p='BNA'+new Date().getFullYear();let m=0;if(sh.getLastRow()>1)sh.getRange(2,2,sh.getLastRow()-1,1).getValues().flat().forEach(v=>{const x=s(v).match(new RegExp('^'+p+'(\\d{5})$'));if(x)m=Math.max(m,+x[1])});return p+String(m+1).padStart(5,'0')}
function verifyStudent(ss,d){const id=s(d.studentId).toUpperCase(),email=s(d.email).toLowerCase();if(!id||!email)throw Error('Student ID and registered email are required.');const r=sheet(ss,'Students').getDataRange().getValues();for(let i=1;i<r.length;i++)if(s(r[i][1]).toUpperCase()===id&&s(r[i][3]).toLowerCase()===email)return{ok:true,message:'Student verified.',student:{studentId:id,name:s(r[i][2]),email:s(r[i][3]),phone:s(r[i][4]),status:s(r[i][7])}};return{ok:false,message:'Student ID and email do not match.'}}
function studentDashboard(ss,d){const v=verifyStudent(ss,d);if(!v.ok)return v;const id=v.student.studentId;const rows=n=>sheet(ss,n).getDataRange().getValues().slice(1).filter(r=>s(r[1]).toUpperCase()===id);return{ok:true,student:v.student,enrollments:rows('Enrollments'),payments:rows('Payments'),results:rows('Results'),certificates:rows('Certificates'),courses:getCourses(ss)}}
function adminLogin(d){const pass=prop('ADMIN_PASSWORD','');return pass&&s(d.password)===pass?{ok:true,message:'Admin login successful.'}:{ok:false,message:'Invalid admin password. Set ADMIN_PASSWORD in Script Properties.'}}
function requireAdmin(d){const pass=prop('ADMIN_PASSWORD','');if(!pass||s(d.password)!==pass)throw Error('Admin authorization failed.')}
function adminData(ss){return{ok:true,students:sheet(ss,'Students').getDataRange().getValues(),courses:sheet(ss,'Courses').getDataRange().getValues(),enrollments:sheet(ss,'Enrollments').getDataRange().getValues(),payments:sheet(ss,'Payments').getDataRange().getValues(),results:sheet(ss,'Results').getDataRange().getValues(),certificates:sheet(ss,'Certificates').getDataRange().getValues()}}
function course(ss,id){return getCourses(ss).find(x=>String(x.id)===String(id))||null}
function enrollDirect(ss,d){const student=s(d.studentId).toUpperCase(),c=course(ss,d.courseId);if(!student||!c)throw Error('Valid Student ID and Course ID are required.');const sh=sheet(ss,'Enrollments'),r=sh.getDataRange().getValues();for(let i=1;i<r.length;i++)if(s(r[i][1]).toUpperCase()===student&&String(r[i][2])===String(c.id)){sh.getRange(i+1,4).setValue(c.name);sh.getRange(i+1,5).setValue(c.subjects||'');sh.getRange(i+1,6).setValue('ACTIVE');sh.getRange(i+1,7).setValue('PAID');return{ok:true,message:'Enrollment activated.',studentId:student,courseId:c.id}}sh.appendRow([new Date(),student,c.id,c.name,c.subjects||'','ACTIVE','PAID']);return{ok:true,message:'Direct enrollment successful.',studentId:student,courseId:c.id,fee:0}}
function upsertEnrollment(ss,d){return enrollDirect(ss,d)}
function adminCourseAdd(ss,d){const name=s(d.course)||s(d.name);if(!name)throw Error('Course name is required.');const sh=sheet(ss,'Courses'),id=nextCourseId(sh);sh.appendRow([id,name,0,s(d.subjects),'Active']);return{ok:true,message:'Course added with zero fee.',course:{id,name,fee:0,status:'Active'}}}
function nextCourseId(sh){let m=0;if(sh.getLastRow()>1)sh.getRange(2,1,sh.getLastRow()-1,1).getValues().flat().forEach(v=>{const n=Number(v);if(n>m)m=n});return m+1}
function adminPaymentVerify(ss,d){const sh=sheet(ss,'Payments'),id=s(d.paymentId),order=s(d.orderId),student=s(d.studentId).toUpperCase();if(!id&&!order&&!student)throw Error('Payment ID, Order ID or Student ID is required.');let found=false,foundStudent=student,foundCourse=d.courseId,foundName=d.course;if(sh.getLastRow()>1){const r=sh.getDataRange().getValues();for(let i=1;i<r.length;i++){if((id&&s(r[i][5])===id)||(order&&s(r[i][6])===order)||(student&&s(r[i][1]).toUpperCase()===student&&String(d.courseId||'')===String(r[i][2]||''))){sh.getRange(i+1,8).setValue('Paid');found=true;foundStudent=s(r[i][1]).toUpperCase();foundCourse=r[i][2];foundName=r[i][3];break}}}if(!found){if(!student)throw Error('Payment record not found.');sh.appendRow([new Date(),student,s(d.courseId),s(d.course),0,id,order,'Paid'])}upsertEnrollment(ss,{studentId:foundStudent,courseId:foundCourse,course:foundName});return{ok:true,verified:true,paymentStatus:'Paid',enrollmentStatus:'ACTIVE',studentId:foundStudent,courseId:foundCourse,message:'Fee verified and enrollment activated.'}}
function adminResult(ss,d){saveResult(ss,d);return{ok:true,message:'Result uploaded.'}}
function adminResultBulk(ss,d){const list=Array.isArray(d.results)?d.results:[];if(!list.length)throw Error('No subject marks supplied.');const lock=LockService.getScriptLock();lock.waitLock(30000);try{list.forEach(x=>validateResult(Object.assign({},d,x)));list.forEach(x=>saveResult(ss,Object.assign({},d,x)));return{ok:true,message:list.length+' subject result(s) uploaded.'}}finally{lock.releaseLock()}}
function validateResult(d){const score=Number(d.score),total=Number(d.maxMarks||d.total||0),subjectId=s(d.subjectId)||s(d.subject);if(!subjectId)throw Error('Subject ID is required.');if(isNaN(score))throw Error('Marks must be numeric.');if(total<=0)throw Error('Total marks must be greater than zero.');if(score<0||score>total)throw Error('Marks for '+subjectId+' must be between 0 and '+total+'.')}
function saveResult(ss,d){validateResult(d);const studentId=s(d.studentId).toUpperCase(),name=s(d.name),courseId=s(d.courseId),courseName=s(d.course),subjectId=s(d.subjectId)||s(d.subject),subject=s(d.subject),score=Number(d.score),total=Number(d.maxMarks||d.total),minPass=Number(d.minPassMarks||0),percentage=total?Math.round(score/total*10000)/100:0,result=(minPass?score>=minPass:percentage>=40)?'PASS':'FAIL',sh=sheet(ss,'Results');const rows=sh.getDataRange().getValues();const matches=[];for(let i=1;i<rows.length;i++){if(s(rows[i][1]).toUpperCase()===studentId&&s(rows[i][3])===courseId&&s(rows[i][5])===subjectId)matches.push(i+1)}const values=[new Date(),studentId,name,courseId,courseName,subjectId,subject,score,total,percentage,result];if(matches.length){sh.getRange(matches[0],1,1,values.length).setValues([values]);for(let i=matches.length-1;i>=1;i--)sh.deleteRow(matches[i]);}else sh.appendRow(values)}
function saveCertificate(ss,d){const sh=sheet(ss,'Certificates'),no=s(d.certificateNo)||('BNA-CERT-'+new Date().getFullYear()+'-'+String(sh.getLastRow()).padStart(5,'0'));sh.appendRow([new Date(),s(d.studentId),s(d.name),s(d.courseId),s(d.course),no,s(d.grade),new Date(),s(d.verificationUrl)]);return no}